### ISSUE TITLE
Figuranten Overview list

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/FigurantManagement#6]
The current system is not user friendly.

We need a table like structure, with the top line having ways to filter and re-order the lists, all filters / lists need a way to invert the list too.

Search / Filter suggestions:

- list & search alphabetically by character name
- list & search alphabetically by figu name
- list by date of creation
- list & filter by faction
- filter with search match on

All these filters need to be able to run concurently - so that multi-match is possible.
Just hide if any of the filters should exclude it.

Have each entry be a full horizontal bar with the apropriate fields & buttons, where it only turns into a card if there isn't enough screenspace.

**Comment by SulpherStaer** [comment]
Changed priority, as this function is required for another issue;
https://github.com/eosfrontier/PersonaGenerator/issues/5

**Comment by WafflesMcDuff** [comment]
@SulpherStaer  - I think at this point you have the API endpoints you need for me to hand this over, correct?

**Comment by SulpherStaer** [comment]
Correct. This is now on my end. I still haven't found the energy to actually do anything yet.
